attach(inventory)
head(inventory)
plot(`DBH (cm)`, `Height(m)`, main="Scatterplot")
cor(`DBH (cm)`, `Height(m)`)
mod <-lm (`Height(m)`~ `DBH (cm)`)
summary(mod)
abline(mod, col=2, lwd=3)
deattach(inventory)
rm(inventory)
q()
